ALTER TABLE member
    ALTER COLUMN id RESTART WITH 8;
ALTER TABLE store
    ALTER COLUMN id RESTART WITH 4;
ALTER TABLE waiting_line
    ALTER COLUMN id RESTART WITH 4;
ALTER TABLE waiting_member
    ALTER COLUMN id RESTART WITH 4;
